### ISSUE TITLE
Pipeline step `archiveArtifacts` is incorrectly associated with Synopsys Detect

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/pipeline-steps-doc-generator#321] opened 2023-06-15 05:56 UTC
### Service(s)

jenkins.io

### Summary

Filing here because it's probably more of a issue with https://github.com/jenkins-infra/pipeline-steps-doc-generator/

It's weird that a core-provided step is listed in a seemingly random plugin: https://www.jenkins.io/doc/pipeline/steps/blackduck-detect/#archiveartifacts-archive-the-artifacts

### Reproduction steps

1. Go to https://www.jenkins.io/doc/pipeline/steps/
2. Search for `archiveArtifacts`

**Comment by MarkEWaite** [comment] 2023-06-26 10:43
I suspect the problem is related to the same issue that prompted

* https://github.com/jenkins-infra/update-center2/pull/716

The blackduck-detect plugin release 8.0.0 incorrectly includes many plugins within its `hpi` file.  I suspect that the Pipeline steps doc generator sees the help from one or more of those incorrectly embedded plugins and adds that help to the blackduck-detect page for the Pipeline steps reference.

**Comment by MarkEWaite** [comment] 2023-07-03 02:08
Resolved by the release of Synopsys detect plugin 8.0.1.  It removed the incorrect inclusion of a large number of plugins into the hpi file.  https://github.com/jenkinsci/synopsys-detect-plugin/releases/tag/8.0.1 documents the release.

https://www.jenkins.io/doc/pipeline/steps/blackduck-detect/ now has the correct content.

**Closed by MarkEWaite** 2023-07-03 02:08 UTC
